from math import log2


def above_threshold_at_n(feedback_model_scores: list[float], threshold_score: float, n: int) -> int:
    """
    This function computes a custom metric, which calculates how many more relevant responses
    we obtain during the 2nd retrieval iteration (vanilla or relevance feedback-based).

    In the 1st iteration, we already retrieved the top #CONTEXT_LIMIT of responses and rescored them with the feedback
    model.
    The most relevant document in this set (from the perspective of the feedback model) has a `threshold_score`.

    The second retrieval iteration is helpful only if it provides responses that are at least as relevant to the query
    (with a relevance score >= than the threshold score from the perspective of the feedback model).

    With a golden list of `feedback_model_scores` corresponding to responses retrieved & ranked by an
    evaluated method (vanilla or relevance feedback–based retrieval),
    we can calculate which method provides more results above the relevance threshold (i.e., desired ones)
    within the top-N responses.

    This function returns the number of these desired results within the top-N responses.

    Args:
        feedback_model_scores (List[float]): The list of relevance scores generated by the feedback model for each
        response of the 2nd retrieval iteration, presented in the order they were retrieved.
        threshold_score (float): The threshold score, baseline for desired relevance.
        n (int): The number of top responses to consider in the metric.

    Returns:
        int: Number of more relevant than the threshold responses within the top-N.
    """
    return sum(1 for i in range(n) if feedback_model_scores[i] >= threshold_score)


def relative_relevance_gain(
    total_relevance_feedback_above_threshold_at_n: int, total_vanilla_above_threshold_at_n: int
) -> float:
    """
    Computes the relative relevance gain of using relevance feedback-based over vanilla retrieval
    based on the sum of above_threshold_at_n scores across all eval queries."

    Args:
        total_relevance_feedback_above_threshold_at_n (int): Total count of relevant results above the threshold
            retrieved by the relevance feedback method.
        total_vanilla_above_threshold_at_n (int): Total count of relevant results above the threshold
            retrieved by the vanilla method.

    Returns:
        float: The relative gain percentage if relevance feedback is strictly better and vanilla retrieval
            found at least one relevant result. Returns 0.0 otherwise.
    """
    if total_relevance_feedback_above_threshold_at_n > total_vanilla_above_threshold_at_n > 0:
        return (
            (total_relevance_feedback_above_threshold_at_n - total_vanilla_above_threshold_at_n)
            / total_vanilla_above_threshold_at_n
            * 100
        )
    return 0.0


class DcgWinRate:
    """
    Discounted Cumulative Gain (DCG) Win Rate metric.

    This metric measures the percentage of queries where one retrieval method outperforms another
    in terms of the Discounted Cumulative Gain (DCG) of the retrieved responses.
    The relevance of responses is determined by the feedback model scores.

    For each query, we compute DCG@N for both methods. The method with the higher DCG gets a "win".
    If DCG values are equal, it is counted as a "tie".

    Args:
        n (int): The cutoff rank for DCG calculation (DCG@N).
    """
    def __init__(self, n: int):
        self.left_wins = 0
        self.right_wins = 0
        self.ties = 0
        self.n = n

    def add(self, feedback_model_scores_left: list[float], feedback_model_scores_right: list[float]):
        """
        Updates the win/tie counts based on the comparison of two methods for a single query.

        Args:
            feedback_model_scores_left (List[float]): Feedback model scores for the responses retrieved by the left
                method.
            feedback_model_scores_right (List[float]): Feedback model scores for the responses retrieved by the right
                method.
        """
        # Calculate DCG@N for both methods
        # DCG = sum(score / log2(rank + 1))
        left_dcg = sum((score / log2(rank + 1)) for rank, score in enumerate(feedback_model_scores_left[:self.n], 1))
        right_dcg = sum((score / log2(rank + 1)) for rank, score in enumerate(feedback_model_scores_right[:self.n], 1))

        # If there was a tie, no one wins
        if left_dcg > right_dcg:
            self.left_wins += 1
        elif left_dcg < right_dcg:
            self.right_wins += 1
        else:
            self.ties += 1

    def evaluate_left(self) -> float:
        """Calculate the win rate of the left method.

        Returns:
            float: Percentage of queries where the left method outperformed the right method.
        """
        total = self.left_wins + self.right_wins + self.ties
        if total == 0:
            return 0.0
        return self.left_wins * 100 / total

    def evaluate_right(self) -> float:
        """Calculate the win rate of the right method.

        Returns:
            float: Percentage of queries where the right method outperformed the left method.
        """
        total = self.left_wins + self.right_wins + self.ties
        if total == 0:
            return 0.0
        return self.right_wins * 100 / total

    def evaluate_ties(self) -> float:
        """Calculate the tie rate between the methods.

        Returns:
            float: Percentage of queries where both methods achieved the same DCG score.
        """
        total = self.left_wins + self.right_wins + self.ties
        if total == 0:
            return 0.0
        return self.ties * 100 / total

